//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_User
    {
        public string User_ID { get; set; }
        public string User_LoginName { get; set; }
        public string User_LoginPassword { get; set; }
        public string User_MobilePhone { get; set; }
        public string User_NickName { get; set; }
        public string User_Email { get; set; }
        public string User_Pic { get; set; }
        public Nullable<System.DateTime> User_RegTime { get; set; }
        public string User_RegIP { get; set; }
        public Nullable<int> User_Status { get; set; }
        public string WeChat_Open_Id { get; set; }
        public Nullable<int> Del { get; set; }
        public Nullable<System.DateTime> Operation { get; set; }
        public string Operator { get; set; }
    }
}
