//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_Shop
    {
        public string Shop_ID { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_Tel { get; set; }
        public string Shop_LinkMan { get; set; }
        public string Prov_ID { get; set; }
        public string City_ID { get; set; }
        public string Area_ID { get; set; }
        public string Shop_Address { get; set; }
        public string CommerceGroup_ID { get; set; }
        public string Shop_RechargePassword { get; set; }
        public System.DateTime Shop_OpenDate { get; set; }
        public System.DateTime Shop_EndDate { get; set; }
        public int Shop_SmsCount { get; set; }
        public string Shop_Logo { get; set; }
        public string Shop_longitude { get; set; }
        public string Shop_latitude { get; set; }
        public string Shop_BusinessTime { get; set; }
        public int Shop_Status { get; set; }
        public string Merchant_ID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public byte[] OptionTimestamp { get; set; }
        public Nullable<decimal> Deliveryamount { get; set; }
        public Nullable<decimal> Takeoutcost { get; set; }
        public string TakeOutTimeBegin { get; set; }
        public string TakeOutTimeEnd { get; set; }
        public Nullable<bool> TakeOutStatus { get; set; }
        public Nullable<bool> PayOnDelivery { get; set; }
        public Nullable<bool> BookStatus { get; set; }
        public Nullable<bool> BookBasketStatus { get; set; }
        public Nullable<int> AnticipationType { get; set; }
        public Nullable<decimal> AnticipationAmount { get; set; }
        public Nullable<decimal> AnticipationRate { get; set; }
        public string BookSmsTel { get; set; }
        public string BookSmsEmployeeID { get; set; }
        public string TakeOutSmsTel { get; set; }
        public string TakeOutSmsEmployeeID { get; set; }
    }
}
