//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_MerchantProducts
    {
        public string Product_ID { get; set; }
        public string MerchantBaseInfo_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Code { get; set; }
        public string Product_SpellCode { get; set; }
        public string Product_Unit { get; set; }
        public decimal Product_Price { get; set; }
        public string Product_BPic { get; set; }
        public string Product_SPic { get; set; }
        public int Product_Discount { get; set; }
        public int Combo { get; set; }
        public string Product_Memo { get; set; }
        public string Merchant_ID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public byte[] OptionTimestamp { get; set; }
    }
}
