//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_WeChat
    {
        public string WeChat_ID { get; set; }
        public string Original_ID { get; set; }
        public Nullable<int> WeChatType { get; set; }
        public string WeChatName { get; set; }
        public string WechatNumber { get; set; }
        public string APPID { get; set; }
        public string AppSecret { get; set; }
        public string Token { get; set; }
        public string EncodingAESKey { get; set; }
        public string Mch_ID { get; set; }
        public string PayKey { get; set; }
        public int Status { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Operator { get; set; }
    }
}
