//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_WeChatToken
    {
        public string WeChatToken_ID { get; set; }
        public string WeChat_ID { get; set; }
        public string Original_ID { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> Access_Time { get; set; }
        public string JsApiTicket { get; set; }
        public Nullable<System.DateTime> Ticket_Time { get; set; }
    }
}
