//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_Merchant
    {
        public string Merchant_ID { get; set; }
        public string Server_ID { get; set; }
        public string Merchant_Name { get; set; }
        public string Merchant_ShortName { get; set; }
        public string MerchantClass_ID { get; set; }
        public string Merchant_Linkman { get; set; }
        public string Merchant_Tel { get; set; }
        public string Merchant_Fax { get; set; }
        public string Merchant_Email { get; set; }
        public string Merchant_QQ { get; set; }
        public string Merchant_Prov { get; set; }
        public string Merchant_City { get; set; }
        public string Merchant_Area { get; set; }
        public string Merchant_Address { get; set; }
        public System.DateTime Merchant_FDate { get; set; }
        public System.DateTime Merchant_LDate { get; set; }
        public int Merchant_Status { get; set; }
        public int Merchant_OpenApp { get; set; }
        public int Merchant_OpenWeb { get; set; }
        public int Merchant_OpenWeixin { get; set; }
        public string Merchant_Number { get; set; }
        public string Merchant_Password { get; set; }
        public string Merchant_Memo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string Operator { get; set; }
        public byte[] OptionTimestamp { get; set; }
        public Nullable<int> Del { get; set; }
    }
}
