//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_MerchantImg
    {
        public string Img_ID { get; set; }
        public string Img_Url { get; set; }
        public Nullable<int> Img_Type { get; set; }
        public Nullable<int> Img_IsIndex { get; set; }
        public string Merchant_ID { get; set; }
    }
}
