//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_Coupon
    {
        public string Coupon_ID { get; set; }
        public string MerchantBaseInfo_ID { get; set; }
        public string Coupon_Name { get; set; }
        public string Coupon_Code { get; set; }
        public string Coupon_BriefCode { get; set; }
        public int Coupon_Class { get; set; }
        public string Product_ID { get; set; }
        public int Coupon_ConsumeClass { get; set; }
        public decimal Coupon_Cash { get; set; }
        public int Coupon_UserNum { get; set; }
        public string Coupon_Unit { get; set; }
        public decimal Coupon_BuyPrice { get; set; }
        public decimal Coupon_DeductionPrice { get; set; }
        public int Coupon_Validity { get; set; }
        public Nullable<System.DateTime> Coupon_FDate { get; set; }
        public Nullable<System.DateTime> Coupon_LDate { get; set; }
        public Nullable<int> Coupon_DateNum { get; set; }
        public int Coupon_IntegralExchange { get; set; }
        public Nullable<decimal> Coupon_Integral { get; set; }
        public string Coupon_BPic { get; set; }
        public string Coupon_SPic { get; set; }
        public int Coupon_Status { get; set; }
        public string Merchant_ID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public string Memo { get; set; }
    }
}
