//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_BossReport
    {
        public string BossReport_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string BossReportName { get; set; }
        public int SendTime { get; set; }
        public int Status { get; set; }
        public string ReceiveMobilePhone { get; set; }
        public string ShopList { get; set; }
        public string Memo { get; set; }
        public int BusinessBeginHour { get; set; }
        public int BusinessBeginMinute { get; set; }
        public int BusinessDate { get; set; }
        public int BusinessEndHour { get; set; }
        public int BusinessEndMinute { get; set; }
        public Nullable<int> SendCycle { get; set; }
        public int MemberIncrease { get; set; }
        public int CardIncrease { get; set; }
        public Nullable<int> ConsumeTotal { get; set; }
        public int MemberConsumeTotal { get; set; }
        public int MemberRechargeTotal { get; set; }
        public int MemberRechargeGiveTotal { get; set; }
        public int IndividualConsumeTotal { get; set; }
        public int MemberReductionTotal { get; set; }
        public int CouponRechargeQuantity { get; set; }
        public int CouponUseQuantity { get; set; }
        public int MemberAddIntegral { get; set; }
        public int MemberReductionIntegral { get; set; }
        public int MemberMoneyTotal { get; set; }
        public int MemberIntegralTotal { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> LastExecDate { get; set; }
        public Nullable<int> Del { get; set; }
    }
}
