//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_GivenCoupon
    {
        public string GivenCoupon_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Record_ID { get; set; }
        public int GivenCoupon_Type { get; set; }
        public string Coupon_ID { get; set; }
        public int CouponQuantity { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
