//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_MarketingAnalyze
    {
        public string MarketingAnalyze_ID { get; set; }
        public string MarketingAnalyze_Name { get; set; }
        public string Merchant_ID { get; set; }
        public Nullable<int> AutoExec { get; set; }
        public Nullable<int> AgeStart { get; set; }
        public Nullable<int> AgeEnd { get; set; }
        public Nullable<int> Sex { get; set; }
        public string CardDiscountType_ID { get; set; }
        public Nullable<decimal> ResidueIntegralStart { get; set; }
        public Nullable<decimal> ResidueIntegralEnd { get; set; }
        public Nullable<decimal> ResidueMoneyStart { get; set; }
        public Nullable<decimal> ResidueMoneyEnd { get; set; }
        public Nullable<int> OpenCardValidity { get; set; }
        public Nullable<System.DateTime> OpenCardDateStart { get; set; }
        public Nullable<System.DateTime> OpenCardDateEnd { get; set; }
        public Nullable<int> BirthdayValidity { get; set; }
        public string BirthdayStart { get; set; }
        public string BirthdayEnd { get; set; }
        public Nullable<System.DateTime> ConsumeDateStart { get; set; }
        public Nullable<System.DateTime> ConsumeDateEnd { get; set; }
        public Nullable<int> ConsumeCountStart { get; set; }
        public Nullable<int> ConsumeCountEnd { get; set; }
        public Nullable<decimal> SimpleConsumeMoneyStart { get; set; }
        public Nullable<decimal> SimpleConsumeMoneyEnd { get; set; }
        public Nullable<decimal> CountCunsumeMoneyStart { get; set; }
        public Nullable<decimal> CountCunsumeMoneyEnd { get; set; }
        public Nullable<int> RechargeCountStart { get; set; }
        public Nullable<int> RechargeCountEnd { get; set; }
        public Nullable<decimal> SimpleRechargeMoneyStart { get; set; }
        public Nullable<decimal> SimpleRechargeMoneyEnd { get; set; }
        public Nullable<decimal> CountRechargeMoneyStart { get; set; }
        public Nullable<decimal> CountRechargeMoneyEnd { get; set; }
        public Nullable<int> SimpleConsumePeopleStart { get; set; }
        public Nullable<int> SimpleConsumePeopleEnd { get; set; }
        public Nullable<int> CountIntegralDeductionStart { get; set; }
        public Nullable<int> CountIntegralDeductionEnd { get; set; }
        public Nullable<int> NotConsumeDay { get; set; }
        public Nullable<decimal> IntegralTotalStart { get; set; }
        public Nullable<decimal> IntegralTotalEnd { get; set; }
        public string ConsumeProduct_ID { get; set; }
        public Nullable<int> CountConsumeProductStart { get; set; }
        public Nullable<int> CountConsumeProductEnd { get; set; }
        public string ConsumeCoupon_ID { get; set; }
        public Nullable<int> StatisticsTotal { get; set; }
        public Nullable<int> IssueTotal { get; set; }
        public Nullable<decimal> GivenIntegral { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> LastExeTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
    }
}
