//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_Member
    {
        public string Member_ID { get; set; }
        public string Member_Name { get; set; }
        public string Member_Sex { get; set; }
        public string Member_MobilePhone { get; set; }
        public string Member_HomePhone { get; set; }
        public string Member_Code { get; set; }
        public Nullable<System.DateTime> Member_Birthday { get; set; }
        public string Member_Email { get; set; }
        public string Member_Logo { get; set; }
        public System.DateTime Member_RegisterTime { get; set; }
        public string Member_Memo { get; set; }
        public string User_ID { get; set; }
        public Nullable<System.DateTime> Operation { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public byte[] OptionTimestamp { get; set; }
    }
}
