//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_ShopIntegralProducts
    {
        public string ShopIntegralProduct_ID { get; set; }
        public string IntegralProduct_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Dictionary_ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string SpellCode { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public string BPic { get; set; }
        public string SPic { get; set; }
        public string Memo { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public byte[] OptionTimestamp { get; set; }
    }
}
