//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_SmsMember
    {
        public string SmsMember_ID { get; set; }
        public string Sms_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Member_ID { get; set; }
        public string MobilePhone { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string BackStatus { get; set; }
        public string FailMsg { get; set; }
    }
}
