//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_BookOrderPay
    {
        public string BookOrderPay_ID { get; set; }
        public int PayType { get; set; }
        public decimal PayMoney { get; set; }
        public System.DateTime PayTime { get; set; }
        public string Book_ID { get; set; }
        public string Card_ID { get; set; }
        public string Card_BusinessID { get; set; }
        public string User_ID { get; set; }
        public string Pay_JyNum { get; set; }
        public Nullable<int> Adjust { get; set; }
        public Nullable<int> Del { get; set; }
    }
}
