//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Arrears
    {
        public string Arrears_ID { get; set; }
        public string Member_ID { get; set; }
        public string Order_ID { get; set; }
        public Nullable<decimal> Arrears_Money { get; set; }
        public Nullable<int> Arrears_Status { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public string Pay_Card_ID { get; set; }
        public string PayMemo { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
