//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_AppInstruction
    {
        public string Instruction_ID { get; set; }
        public Nullable<int> InstructionType { get; set; }
        public string InstructionData { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SendCallBack { get; set; }
        public string SendCallBackClient_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Member_ID { get; set; }
    }
}
