//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Sms
    {
        public string Sms_ID { get; set; }
        public System.DateTime SendTime { get; set; }
        public string SmsContent { get; set; }
        public int SmsQuantity { get; set; }
        public int SmsType { get; set; }
        public int Status { get; set; }
        public string Memo { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> Operation { get; set; }
    }
}
