//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_ThirdPay
    {
        public string ThirdPay_ID { get; set; }
        public int BusinessClass { get; set; }
        public string Record_ID { get; set; }
        public string Member_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public int PayType { get; set; }
        public string PayBussinessNum { get; set; }
        public decimal PayMoney { get; set; }
        public int PayStatus { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> PayOverTime { get; set; }
        public string BusinessJSON { get; set; }
    }
}
