//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_OrderBasket
    {
        public string Bask_ID { get; set; }
        public string Order_ID { get; set; }
        public string Product_ID { get; set; }
        public string ShopProduct_ID { get; set; }
        public string Bask_Units { get; set; }
        public Nullable<decimal> Bask_Price { get; set; }
        public Nullable<int> Bask_Count { get; set; }
        public Nullable<int> Bask_Discount { get; set; }
        public Nullable<decimal> Bask_Total { get; set; }
        public string Bask_Zuofa { get; set; }
        public Nullable<int> Bask_Status { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Member_ID { get; set; }
        public string User_ID { get; set; }
        public Nullable<int> Bask_PrintStatus { get; set; }
        public Nullable<int> Bask_Terminal { get; set; }
        public Nullable<int> Bask_ScCount { get; set; }
        public Nullable<int> Bask_GivenCount { get; set; }
        public Nullable<int> Bask_ReturnCount { get; set; }
        public string Combo { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<int> Del { get; set; }
        public byte[] OptionTimestamp { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
