//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_AutoPromotionRecord
    {
        public string PromotionRecord_ID { get; set; }
        public string Promotion_ID { get; set; }
        public string PromotionName { get; set; }
        public string PromotionType { get; set; }
        public Nullable<double> GivenIntegral { get; set; }
        public string Coupon_ID { get; set; }
        public Nullable<int> CouponQuantity { get; set; }
        public string BusinessClass { get; set; }
        public string Record_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Card_ID { get; set; }
        public string Card_BusinessID { get; set; }
        public string Member_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Memo { get; set; }
        public string ExecuteYear { get; set; }
        public Nullable<System.DateTime> ExecuteTime { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
