//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_CardCoupon
    {
        public string CardCoupon_ID { get; set; }
        public string Coupon_ID { get; set; }
        public string Coupon_Name { get; set; }
        public int BusinessClass { get; set; }
        public string Record_ID { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string Order_ID { get; set; }
        public string Card_ID { get; set; }
        public string Card_BusinessID { get; set; }
        public string Merchant_ID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
