//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Reservation
    {
        public string Reservation_ID { get; set; }
        public string Reservation_MobilePhone { get; set; }
        public string Reservation_Name { get; set; }
        public Nullable<int> Reservation_People { get; set; }
        public Nullable<System.DateTime> Reservation_Time { get; set; }
        public Nullable<int> Reservation_Status { get; set; }
        public Nullable<int> Reservation_Change { get; set; }
        public string Seat_ID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> PayType { get; set; }
        public decimal PayMoney { get; set; }
        public string Message { get; set; }
        public string Memo { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Member_ID { get; set; }
        public string Order_ID { get; set; }
        public string User_ID { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public string Terminal { get; set; }
    }
}
