//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_OrderDeliverys
    {
        public string Order_ID { get; set; }
        public string Phone { get; set; }
        public string Consignee { get; set; }
        public string Address { get; set; }
        public bool PayOnDelivery { get; set; }
        public System.DateTime ExpectTime { get; set; }
        public decimal DeliveryFee { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string DeliveryMan { get; set; }
        public string DeliveryPhone { get; set; }
        public Nullable<System.DateTime> EstimateTime { get; set; }
        public string Memo { get; set; }
    }
}
