//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_SmsYZMRecord
    {
        public string YZM_ID { get; set; }
        public string YZM_MobilePhone { get; set; }
        public string YZM_Value { get; set; }
        public int YZM_Class { get; set; }
        public int YZM_Status { get; set; }
        public Nullable<System.DateTime> YZM_Time { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Terminal { get; set; }
    }
}
