//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_BookOrders
    {
        public string Book_ID { get; set; }
        public string Business_Num { get; set; }
        public string SN { get; set; }
        public string Phone { get; set; }
        public string Contacts { get; set; }
        public Nullable<int> People { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> Change { get; set; }
        public string ShopSeatClass_ID { get; set; }
        public string Seat_ID { get; set; }
        public string Reason { get; set; }
        public string Memo { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Member_ID { get; set; }
        public string Order_ID { get; set; }
        public string User_ID { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public string Terminal { get; set; }
    }
}
