//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_SmsBusiness
    {
        public string SmsBusiness_Id { get; set; }
        public Nullable<int> SmsType { get; set; }
        public Nullable<int> BusinessClass { get; set; }
        public string Business_Num { get; set; }
        public System.DateTime SendTime { get; set; }
        public string SmsContent { get; set; }
        public byte Status { get; set; }
        public string MobilePhone { get; set; }
        public int SmsSendQuantity { get; set; }
        public Nullable<int> SmsOkQuantity { get; set; }
        public string Back_SmsId { get; set; }
        public string Back_Status { get; set; }
        public string Back_DTime { get; set; }
        public string Back_Desc { get; set; }
        public string FailMsg { get; set; }
        public string Member_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
    }
}
