//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_CardRechargeRecord
    {
        public string RechargeRecord_ID { get; set; }
        public string Business_Num { get; set; }
        public decimal RechargeMoney { get; set; }
        public decimal PayMoney { get; set; }
        public decimal GivenMoney { get; set; }
        public int PayType { get; set; }
        public decimal GivenIntegral { get; set; }
        public string Card_ID { get; set; }
        public string Card_BusinessID { get; set; }
        public string Member_ID { get; set; }
        public string Employee_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Del { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
