//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_IntegralChange
    {
        public string IntegralChange_ID { get; set; }
        public string Card_ID { get; set; }
        public string Card_BusinessID { get; set; }
        public int BusinessClass { get; set; }
        public string Record_ID { get; set; }
        public Nullable<decimal> IntegralIncome { get; set; }
        public Nullable<decimal> IntegralConsume { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
