//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_SmsYZM
    {
        public string SmsYZM_Id { get; set; }
        public string SmsYZM_Mob { get; set; }
        public System.DateTime SmsYZM_Time { get; set; }
        public string SmsYZM_YZM { get; set; }
        public string SmsYZM_Memo { get; set; }
        public string SmsYZM_Status { get; set; }
        public string SmsYZM_Terminal { get; set; }
        public string SmsYZM_ReturnCode { get; set; }
        public string SmsYZM_Error { get; set; }
    }
}
