//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Orders
    {
        public string Order_ID { get; set; }
        public string Business_Num { get; set; }
        public string SN { get; set; }
        public int Order_Class { get; set; }
        public int Order_Process { get; set; }
        public int Order_Status { get; set; }
        public string Seat_ID { get; set; }
        public Nullable<int> Order_People { get; set; }
        public decimal ConsumeMoney { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> DiscountMoney { get; set; }
        public Nullable<decimal> CouponMoney { get; set; }
        public Nullable<decimal> IntegralMoney { get; set; }
        public Nullable<decimal> ReduceMantissaMoney { get; set; }
        public Nullable<decimal> FinalMoney { get; set; }
        public Nullable<decimal> ActualIncomeMoney { get; set; }
        public Nullable<int> IsGuaZhang { get; set; }
        public Nullable<decimal> GuaZhangMoney { get; set; }
        public Nullable<decimal> Order_GetIntegral { get; set; }
        public Nullable<int> CloseIntegral { get; set; }
        public string Employee_ID { get; set; }
        public Nullable<System.DateTime> OpenSeatTime { get; set; }
        public Nullable<System.DateTime> FinalTime { get; set; }
        public string Order_Password { get; set; }
        public string Order_Invoice { get; set; }
        public string Merchant_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Member_ID { get; set; }
        public string Card_ID { get; set; }
        public string Card_BusinessID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
        public string Memo { get; set; }
        public string Terminal { get; set; }
        public Nullable<int> Adjust { get; set; }
    }
}
