//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_CardOperationLogs
    {
        public string Log_Id { get; set; }
        public string Merchant_Id { get; set; }
        public string Shop_Id { get; set; }
        public int Log_Type { get; set; }
        public string Log_Content { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Operator { get; set; }
        public string Member_Id { get; set; }
        public string Card_Id { get; set; }
        public string Card_BusinessID { get; set; }
    }
}
