//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mob_CardApply
    {
        public string Apply_ID { get; set; }
        public System.DateTime Apply_Time { get; set; }
        public string Discount_ID { get; set; }
        public string Member_ID { get; set; }
        public string Shop_ID { get; set; }
        public string Merchant_ID { get; set; }
        public Nullable<int> Apply_Status { get; set; }
        public string Member_Name { get; set; }
        public string Member_Sex { get; set; }
        public string Member_MobilePhone { get; set; }
        public Nullable<int> IsSend { get; set; }
        public string Apply_Address { get; set; }
        public string Message { get; set; }
        public string Memo { get; set; }
        public Nullable<byte> Del { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
    }
}
