//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_SystemModule
    {
        public string Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Code { get; set; }
        public int TerminalType { get; set; }
        public string Module_Perent { get; set; }
        public string Memo { get; set; }
    }
}
