//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_MerchantClass
    {
        public string MerchantClass_Id { get; set; }
        public string MerchantClass_Name { get; set; }
        public byte MerchantClass_Del { get; set; }
    }
}
