//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_MerchantContract
    {
        public string Contract_Id { get; set; }
        public string Contract_Num { get; set; }
        public string Contract_CompanyLinkMan { get; set; }
        public string Contract_MerchantLinkMan { get; set; }
        public Nullable<System.DateTime> Contract_FDate { get; set; }
        public Nullable<System.DateTime> Contract_LDate { get; set; }
        public int Contract_Status { get; set; }
        public string Memo { get; set; }
        public string Merchant_Id { get; set; }
        public System.DateTime AddTime { get; set; }
        public int Del { get; set; }
    }
}
