//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkeServer.DataMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Admins
    {
        public string Admin_Id { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_TrueName { get; set; }
        public int Admin_Status { get; set; }
        public string Grop_IdGroup { get; set; }
        public int Del { get; set; }
    }
}
